# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecturecms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='stub',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Stub'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
    ]
