# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=255, verbose_name='People')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(blank=True, verbose_name='Body')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=255, verbose_name='People')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcard.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='postcard.Thread'),
        ),
    ]
