# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('required', models.BooleanField(verbose_name='Required')),
                ('questionText', models.TextField(verbose_name='Question Text')),
                ('typeName', models.CharField(max_length=20, verbose_name='Type')),
                ('answer', models.TextField(verbose_name='Answer Text')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='questions.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.Step'),
        ),
    ]
